### ISSUE TITLE
Program stuck at initial Alignment stage 

### ISSUE THREAD

**Issue by saiafz** [uubram/RTCR#1]
After execution as soon as alignment phase ends, program stucks for hours and there is no progress and needs to be terminated.
There are no errors. Can you please guide about it?

**Comment by uubram** [comment]
Currently, there is no progress bar implemented at the error correction stage. For large datasets the program can take many hours to complete, so it may not be truly stuck. To check if it is doing something you could run rtcr with the "--debug" flag, for example:
rtcr run --reads myreads.fq --debug

This should cause the pipeline to produce regular log messages to rtcr.log, showing which clones it is merging during error correction.

**Comment by saiafz** [comment]
This is how it looks when run according to your instructions. Please see below.
And it has this problem even with your provided dataset, And actually there are no errors in log file.



2016-11-29 16:20:56,921 - MainProcess - DEBUG - log level set to DEBUG
2016-11-29 16:20:58,822 - MainProcess - DEBUG - species, allele
HomoSapiens, TRBD2*01
HomoSapiens, TRBD1*01

2016-11-29 16:20:58,822 - MainProcess - DEBUG - species, allele
HomoSapiens, TRBJ2-7*01
HomoSapiens, TRBJ2-1*01
HomoSapiens, TRBJ1-3*01
HomoSapiens, TRBJ2-4*01
HomoSapiens, TRBJ1-2*01
HomoSapiens, TRBJ2-2*01
HomoSapiens, TRBJ1-1*01
HomoSapiens, TRBJ2-6*01
HomoSapiens, TRBJ2-5*01
HomoSapiens, TRBJ1-6*01
HomoSapiens, TRBJ1-5*01
HomoSapiens, TRBJ2-3*01
HomoSapiens, TRBJ1-4*01

2016-11-29 16:20:58,822 - MainProcess - DEBUG - species, allele
HomoSapiens, TRBV6-4*01
HomoSapiens, TRBV28*01
HomoSapiens, TRBV11-3*01
HomoSapiens, TRBV24-1*01
HomoSapiens, TRBV12-5*01
HomoSapiens, TRBV6-3*01
HomoSapiens, TRBV19*01
HomoSapiens, TRBV25-1*01
HomoSapiens, TRBV6-8*01
HomoSapiens, TRBV10-3*01
HomoSapiens, TRBV4-1*01
HomoSapiens, TRBV6-5*01
HomoSapiens, TRBV20-1*01
HomoSapiens, TRBV7-2*01
HomoSapiens, TRBV6-2*01
HomoSapiens, TRBV9*01
HomoSapiens, TRBV4-3*01
HomoSapiens, TRBV12-4*01
HomoSapiens, TRBV15*01
HomoSapiens, TRBV30*01
HomoSapiens, TRBV5-4*01
HomoSapiens, TRBV5-6*01
HomoSapiens, TRBV4-2*01
HomoSapiens, TRBV7-3*01
HomoSapiens, TRBV2*01
HomoSapiens, TRBV29-1*01
HomoSapiens, TRBV11-2*01
HomoSapiens, TRBV18*01
HomoSapiens, TRBV7-7*01
HomoSapiens, TRBV7-9*01
HomoSapiens, TRBV16*01
HomoSapiens, TRBV5-1*01
HomoSapiens, TRBV7-6*01
HomoSapiens, TRBV6-9*01
HomoSapiens, TRBV11-1*01
HomoSapiens, TRBV10-2*01
HomoSapiens, TRBV6-6*01
HomoSapiens, TRBV13*01
HomoSapiens, TRBV14*01
HomoSapiens, TRBV5-5*01
HomoSapiens, TRBV7-4*01
HomoSapiens, TRBV12-3*01
HomoSapiens, TRBV5-8*01
HomoSapiens, TRBV27*01
HomoSapiens, TRBV3-1*01
HomoSapiens, TRBV7-8*01
HomoSapiens, TRBV6-1*01
HomoSapiens, TRBV10-1*01

2016-11-29 16:20:58,822 - MainProcess - INFO -
RTCR version: 0.3.1.b
[Files]
Reference: /home/.local/lib/python2.7/site-packages/rtcr-0.3.1.b-py2.7-linux-x86_64.egg/rtcr/immune_receptor_reference.tsv.gz
Reads: /home/RTCR-master/example/reads.fq.gz
Output: results.tsv

[Settings]
PHRED encoding: 33
Species: ['HomoSapiens']
Gene: ['TRB']
confidence: 0.99

[Immune receptor reference]
HomoSapiens,TRB,D: 2 alleles
HomoSapiens,TRB,J: 13 alleles
HomoSapiens,TRB,V: 48 alleles

[Pipeline run]
2016-11-29 16:20:58,842 - MainProcess - INFO - Created temporary directory: "/tmp/tmpmGBhVN"
2016-11-29 16:20:58,843 - MainProcess - INFO - Running command: "/bowtie2-2.2.2/bowtie2-build /tmp/tmpmGBhVN/V_ref.fa /tmp/tmpmGBhVN/V_index"
2016-11-29 16:20:59,207 - MainProcess - INFO - Running command: "/bowtie2-2.2.2/bowtie2 --local -x /tmp/tmpmGBhVN/V_index - --phred33 --threads 8 -D 20 -R 3 -N 0 -i S,1,0.50 -L 8"
2016-11-29 16:20:59,211 - MainProcess - INFO - Running command: "/bowtie2-2.2.2/bowtie2-build /tmp/tmpmGBhVN/J_ref.fa /tmp/tmpmGBhVN/J_index"
2016-11-29 16:20:59,493 - MainProcess - INFO - Running command: "/bowtie2-2.2.2/bowtie2 --local -x /tmp/tmpmGBhVN/J_index - --phred33 --threads 8 -D 20 -R 3 -N 0 -i S,1,0.50 -L 6"

**Comment by saiafz** [comment]
And it remains at this stage and did not progress further. I have allowed even four days, but it had the same issue. Just for information, I have installed RTCR on two different systems, and tried to run it with many different types of datasets, but this problem exists.

**Comment by uubram** [comment]
Thank you for the log details.

I would like to know a few more things that might help me pinpoint the issue:
What hardware, operating system, and python version are you using?
Can you show the analysis directory (dir containing rtcr.log) contents (filenames and filesizes) when the pipeline is stuck on the example dataset?

**Comment by saiafz** [comment]
Thank you.
This is the dir detail when program is run and then stuck
-rw-r--r-- 1 saira developers 102400 2016-11-29 18:02 alignments.sam.gz
-rw-r--r-- 1 saira developers   3055 2016-11-29 18:02 rtcr.log

Python version is 2.7.2
System details Ubuntu 10.04 and 12.04,  64 bit operating system 48 GB of RAM and CPU with eight cores

**Comment by uubram** [comment]
Your alignments.sam.gz is smaller than expected (should be around 300KB), suggesting the alignment phase was incomplete. Can you run the pipeline with the number of threads set to 2? for example:

rtcr run --reads myreads.fq --threads 2

**Comment by saiafz** [comment]
With threads 2 and then with 4 I also tried. This is what I got
-rw-r--r-- 1 saira developers 229376 2016-11-29 18:46 alignments.sam.gz
-rw-r--r-- 1 saira developers   3055 2016-11-29 18:46 rtcr.log

And it is stuck at here;

Aligning reference sequences to reads
[     100.00%(0h:0m:0s remaining)      ] : Alignments


Just remains here like this.

**Comment by uubram** [comment]
I have been unable to reproduce your issue on Ubuntu 12.04 with python 2.7.2 and bowtie2 version 2.2.2.

Are you getting the same issue on other computers?

**Comment by saiafz** [comment]
Unfortunately, yes. I tried on two different systems, but got same issue.

**Comment by saiafz** [comment]
I tried a third system, this time Mac and it worked on Mac. Thank you.
