### ISSUE TITLE
Run rtcr

### ISSUE THREAD

**Issue by sheenaseven** [uubram/RTCR#11]
From the tutorial, **rtcr run -i .../reads.fq.gz** was used. I want to ask how to input R1.fq.gz and R2.fq.gz. Should I firstly combine the R1.fa.gz and R2.fq.gz to reads.fq.gz? like **cat R1.fq.gz, R2.fq.gz>reads.fq.gz**, and then **rtcr run -i .../reads.fq.gz**?

**Comment by uubram** [comment]
All reads that come from the same sample (i.e. sharing the same sequencing run, PCR, and sample barcode) from which TCR sequences might be retrieved should be combined into a single file before running "rtcr run". So you could combine "R1.fq.gz" and "R2.fq.gz" as you mentioned and then run "rtcr run". However, if you have paired-end reads that may be overlapping, these should be paired before running "rtcr run" (see "Analysing a paired-end barcoded HTS dataset" in the RTCR readme for more details).
