### ISSUE TITLE
Tracking fate of a specific CDR3

### ISSUE THREAD

**Issue by jhb1980** [uubram/RTCR#14]
Hey Bram,

this is perhaps a rather specific question, but I was hoping you could facilitate a bit of insight here or via DM... Essentially, I'm currently working with a beta repertoire that contains a known clonal sequence at high clone count (> 40% of T cells - a transgenic model). I can find the perfect CDR3 nt sequence matched in the fastq reads that are fed into RTCR (n = 724,987; ca 15% of all reads). This clone however does not make an appearance in either of results.tsv or discarded_clones.tsv.

N.b.: I can see the CDR3 nucleotide sequence in *_umi_group_ec.fastq (n =16,513 ) and the alignments.sam.gz (n = 43,371).

It would be great to figure out where and why this got dropped? Is there perhaps an issue due to the shear abundance of reads relative to other clones?

**Comment by uubram** [comment]
Perhaps the alignment step is unable to identify the CDR3. You could use `rtcr Convert -i r.dat -o r.tsv` to view the sequences of the clones before any correction is performed.

**Comment by jhb1980** [comment]
No hit in r.tsv, either.... :/

**Comment by uubram** [comment]
That means that the CDR3 was not identified. Are you using the appropriate germline reference V and J genes for the alignments?

**Comment by jhb1980** [comment]
Bingo... I'm working with the MusMusculus reference that comes with the RTCR installation (immune_receptor_reference.tsv.gz). I just ran a quick BLAT (UCSC browser) with the nucleotide sequence upstream of the CDR3 in question, which hits _Trbv14_. Checks out with the reference. However, looking for downstream the J region sequence in UCSC hits _Trbj1-6_. Looking in the reference file, this allele is not listed: only goes up to _TRBJ1-5_ for the mouse alleles. 

Is there a new(er) version of the reference available by any chance? Alternatively, a quick fix would be to add the J sequence manually -- only question then would be what the "Reference postion" integer would need to be...?

**Comment by uubram** [comment]
There is no updated reference yet. You can create a custom reference file and provide it to `rtcr run` using the '--ref' option. The "Reference position" for the J-gene is the index (counting starts from 0) of the first base of the "FGXG" motif (i.e. first base after the CDR3).

**Comment by jhb1980** [comment]
Added the sequence, worked!
