### ISSUE TITLE
Error regarding sequencing quality

### ISSUE THREAD

**Issue by marisolbc** [uubram/RTCR#16]
Hi,

First of all, thank you for developing this tool and congratulations, since it turned out to be the best one for TCR-seq analysis according to a recent [systematic comparison.](https://academic.oup.com/bib/article/21/5/1706/5586920?login=true)

Now to the issue. Everything works fine with the example input in `example/reads.fq.gz`, but when I tried to run RTCR with my fastq samples (from an Ion Torrent S5 platform, offset=33, single-end, non-barcoded) I got the following error:

```
> rtcr run -i ../../../samples/sample_111L.fq -t 40
  Aligning reference sequences to reads

  [      2.01%(0h:0m:30s remaining)      ] : Alignments
  Exception in thread Pipeline:
  Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
    File "/usr/local/lib/python2.7/dist-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/pipeline.py", line 293, in run
      self._clone_classname)
    File "/usr/local/lib/python2.7/dist-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/clone.py", line 536, in build_clone
      other = (nt_jnc, q_jnc, 1))
    File "/usr/local/lib/python2.7/dist-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/clone.py", line 171, in __init__
      super(AnnotatedClone, self).__init__(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/rtcr-0.5.1-py2.7-linux-x86_64.egg/rtcr/clone.py", line 54, in __init__
      self._cqs = ConsensusQSequence(other)
  ValueError: Quality not a valid PHRED score.
```

I do not see anything wrong in my fastq files and I have previously analyzed them with IgBLAST and MiXCR without any issue.

Here is the [rtcr.log](https://github.com/uubram/RTCR/files/6547877/rtcr.log) file, but it does not provide any information about the Phred score error.

 Any clues about this issue? Thank you in advance!

Regards
Marisol.

**Comment by uubram** [comment]
Thank you for the kind words.

The error you show indicates that RTCR came across a quality score outside of the range [0, 41]. Are your reads from a Solexa or PacBio sequencer?

**Comment by marisolbc** [comment]
> Thank you for the kind words.
> 
> The error you show indicates that RTCR came across a quality score outside of the range [0, 41]. Are your reads from a Solexa or PacBio sequencer?

Thank you for the quick response. I have checked it and, indeed, my reads from Ion Torrent have quality scores above 41 (up to 44). What would be the best approach in this situation? Setting to 41 all quality scores above the upper limit or is there any way to tune this parameter in your software?

**Comment by marisolbc** [comment]
I have already fixed my Phred score values and everything works fine now. Thank you for the support!
