### ISSUE TITLE
Get specific UMIs contributing to a final clonotype

### ISSUE THREAD

**Issue by catsutherland** [uubram/RTCR#17]
Hi!
Is there any way to identify the individuals UMIs that have contributed to a final clone from the output that RTCR provides?
i.e. if a clone has a duplicate count of 10, get the 10 unique UMIs that were collapsed down into that clone? I couldn't figure out a way to do this from the output files but I'm not sure if I've missed something. Thanks!

**Comment by uubram** [comment]
Hi catsutherland,

RTCR does not keep track of each UMI assigned to a clone. Doing so could take up a lot of memory.

Best wishes,
Bram

**Comment by catsutherland** [comment]
Thanks for the response! Sounds like we'll have to try another tool to confirm that part of our analysis.
