### ISSUE TITLE
Unable to parse the pattern

### ISSUE THREAD

**Issue by uubram** [uubram/RTCR#19]
Hi Bram,

The above problem was solved. And the alignment was finished successfully and I can see the results.tsv file. However, I got another error shown in the error message of the following command. 

Command:
rtcr run -i ../wt_S1_merged.fastq --species MusMusculus --gene TRA --no_VJ_collapsing -t 8 1>rtcr.log 2>rtcr.err

Error in rtcr.err
Unable to parse the pattern

Do you know what happened? And whether the result file is correct? Thank you  very much!

Best,
Ying

_Originally posted by @wuying1984 in https://github.com/uubram/RTCR/issues/18#issuecomment-1155773673_

**Comment by uubram** [comment]
I have not been able to reproduce your issue. Can you run the command without the "1>rtcr.log 2>rtcr.err" part and share the rtcr.log file with me?

**Comment by wuying1984** [comment]
Hi Bram,

I rerun the command without  "1>rtcr.log 2>rtcr.err" and I did not see the above error. Attached is the log file
[rtcr.log](https://github.com/uubram/RTCR/files/8911746/rtcr.log). Could you please take a look to see if it is correct. Thank you very much!

Best,
Ying

**Comment by uubram** [comment]
It does not look like there is a problem. I think RTCR ran fine.

**Comment by wuying1984** [comment]
That's great. Thank you very much for your instant reply!

Best,
Ying

**Comment by uubram** [comment]
You're welcome.
