### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by emsanz** [uubram/RTCR#2]
Hi!
Just as a comment, you should include the Python version(s) RTCR is working with.

I had an old Python 2.7.11 (if I remember well) and I got errors when installing.
I upgraded to Python 3.6 and it still gave me some errors.
Finally, with Python 2.7.8 I could install it!

Salut!

**Comment by uubram** [comment]
Thank you.

A python 2.7 requirement has been added to the new version of RTCR (0.4.0).
