### ISSUE TITLE
converting MiGEC sample to RTCR, failing at checkout

### ISSUE THREAD

**Issue by jsabatino37** [uubram/RTCR#5]
Hi, 
We have previously used MiGEC for UMI extraction and analysis from Shugay et al 2014.  We would like to try RTCR, but have several questions about how to get started.

We are using the master/slave barcode format that MiGEC uses.  Our samples have already been de-multiplexed for the sample barcode, so we just use the same barcode.txt file for the every sample as shown below:
```
CAGTGgtatcaacgcagagtNNNNtNNNNtNNNNtct  ATTGggcagccctgatt
```
- Does this need to be re-formatted to be compatible with RTCR?  

We tried altering the barcode.txt to 
```
CAGTGgtatcaacgcagagtNNNNNNNNNNNNNNtct
```
and ran the following commands:

```
rtcr Checkout -rc -b barcodes.txt -f R1_001.fastq -r R2_001.fastq
```

We received the following error message:

```
File "/usr/local/bin/rtcr", line 9, in <module>
    load_entry_point('rtcr==0.4.3', 'console_scripts', 'rtcr')()
  File "/usr/local/lib/python2.7/dist-packages/rtcr-0.4.3-py2.7-linux-x86_64.egg/rtcr/__main__.py", line 299, in main
    parse_cmdline()
  File "/usr/local/lib/python2.7/dist-packages/rtcr-0.4.3-py2.7-linux-x86_64.egg/rtcr/__main__.py", line 140, in parse_cmdline
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/rtcr-0.4.3-py2.7-linux-x86_64.egg/rtcr/checkout.py", line 183, in prog_checkout
    adapters = list(BarcodeFormat.records_in(open(barcodes_fn, 'r')))
  File "/usr/local/lib/python2.7/dist-packages/rtcr-0.4.3-py2.7-linux-x86_64.egg/rtcr/fileio.py", line 486, in records_in
    master_adapter = Adapter(fields[1])
IndexError: list index out of range
```
Any help would be appreciated.

Best,
Joe

**Comment by uubram** [comment]
Dear Joe,

The barcode format of RTCR is tab delimited and expects a sample name in the first column, followed by a master barcode, and an optional slave barcode in the 3rd column. See below the re-formatted version of your first barcode.txt:

`S1      CAGTGgtatcaacgcagagtNNNNtNNNNtNNNNtct   ATTGggcagccctgatt`

Hopefully this helps.

Best,
Bram

**Comment by jsabatino37** [comment]
Dear Bram,
This fixed it, thank you!

Best,
Joe
