### ISSUE TITLE
How to determine the correct barcode sequence 

### ISSUE THREAD

**Issue by jessicaluckygirl** [uubram/RTCR#6]
Hello,
   I have met some troubles on data analysis by applying the IMGEC to analyze the data recently.
   Firstly, I don't know what exact barcode sequences should be put into barcode file when de-multiplexing. I use the sequence ((N)2–4CAGTGGTATCAACGCAGAG) as nest PCR primer on the 5′ end of the libraries during the second PCR to increase the diversity. Here I don't  add sample barcode, which can separate by adding index during library construction. 
    Indeed, I have try cagtggtatcaacgcagagtNNNNtNNNNtNNNNtct , as barcode sequence into the barcode file. But the output results is strange, the counts of each clonotype is small. I don't know if there are mistakes during analysis.
   In addition, I don't know if the (N)2-4 at the head of cagtggtatcaacgcagagtNNNNtNNNNtNNNNtct 
would infulence the final results, so I have tried add 2n/3n/4n in front of the cagtggtatcaacgcagagtNNNNtNNNNtNNNNtct , respectievly. By running the pipeline, we get different results, which we can see from attachment below. What's more, there are errors ''UMI size do not match sample size''  when running barcode sequence like 3n/4n in front of the cagtggtatcaacgcagagtNNNNtNNNNtNNNNtct , respectievly.
    Could you give some advices on these questions? What exact sequence should we put into the barcode file? 
    Thanks!
@uubram 

[cagtggtatcaacgcagagtNNNNtNNNNtNNNNtct.txt](https://github.com/uubram/RTCR/files/2196465/cagtggtatcaacgcagagtNNNNtNNNNtNNNNtct.txt)
[nncagtggtatcaacgcagagtNNNNtNNNNtNNNNtct.txt](https://github.com/uubram/RTCR/files/2196466/nncagtggtatcaacgcagagtNNNNtNNNNtNNNNtct.txt)

**Comment by uubram** [comment]
Dear Jessica,

As you mention, your question pertains to how to apply MIGEC to your data. I recommend directing your questions to the people involved in that project (which I am not). Its website is at https://github.com/mikessh/migec. There is a manual available at http://migec.readthedocs.io/en/latest/ that may help you format your barcode sequences.

Lastly, from your description, it seems to me that you should not put the initial (N)2-4, as those are not part of the Unique Molecular Identifier (UMI) that is to be extracted.

I hope this helps.

Best wishes,
Bram

**Comment by jessicaluckygirl** [comment]
Thanks for your suggestions! 
I will try it again.

Jessica
