### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by NilaServaas** [uubram/RTCR#7]
Hi, 

I´m trying to install RTCR using  'python setup.py install' as is mentioned in the manual, but I'm getting the following error: 

Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    with open(path.join(here, 'README.rst')) as f:
IOError: [Errno 2] No such file or directory: '/usr/local/bin/uubram-RTCR-d5388e7/README.rst'

How can this be solved? 

All the best,
Nila

**Comment by uubram** [comment]
Dear Nila,

Thanks for pointing out this issue with setup.py. RTCR has been updated to resolve it (version 0.4.4).

Best wishes,
Bram
